server:
  port: 8081
spring:
  application:
    name: ehr-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.208.1:8848  #nacos地址及端口
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ehr?useUnicode=true&allowMultiQueries=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: p@ssw0rd
  redis:
    jedis:
      pool:
        max-active: 8                     # 连接池最大连接数（使用负值表示没有限制）
        max-idle: -1                      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 8                       # 连接池中的最大空闲连接
        min-idle: 0                       # 连接池中的最小空闲连接
    host: 127.0.0.1                       # Redis服务器地址
    port: 6379                            #redis服务的端口号，默认为6379
    timeout:
  #SpringSecurity关联数据库设置
  main:
    allow-bean-definition-overriding: true
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    #设置当查询结果值为null时，同样映射该查询字段给map。
    call-setters-on-nulls: true
#请求头
jwt.header: Authorization
 #盐值
jwt.base64-secret: meng
#过期时间
jwt.token-validity-in-seconds: 14400000
