server:
  port: 8082
spring:
  application:
    name: ehr-external
  cloud:
    alibaba:
      seata::
      #自定义事务组名称需要与seata-server中的对应
      #（即和config.txt中保持一致）
        tx-service-group: my_test_tx_group
    nacos:
      discovery:
        server-addr: 192.168.208.1:8848  #nacos地址及端口
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ehr_external?useUnicode=true&allowMultiQueries=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: p@ssw0rd
  redis:
    jedis:
      pool:
        max-active: 8                     # 连接池最大连接数（使用负值表示没有限制）
        max-idle: -1                      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 8                       # 连接池中的最大空闲连接
        min-idle: 0                       # 连接池中的最小空闲连接
    host: 127.0.0.1                       # Redis服务器地址
    port: 6379                            #redis服务的端口号，默认为6379
    timeout:
  #SpringSecurity关联数据库设置
  main:
    allow-bean-definition-overriding: true
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    # 是否开启自动驼峰命名规则映射:从数据库列名到Java属性驼峰命名的类似映射
    map-underscore-to-camel-case: true
    # 如果查询结果中包含空值的列，则 MyBatis 在映射的时候，不会映射这个字段
    call-setters-on-nulls: true
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#请求头
jwt.header: token
 #盐值
jwt.base64-secret: meng
#过期时间
jwt.token-validity-in-seconds: 14400000
